### ISSUE TITLE
Paren-completer missing on MELPA.

### ISSUE THREAD

**Issue by ReneFroger** [MatthewBregg/paren-completer#1]
Hi Matthew, thanks for sharing this package! I appreciate it. 

Could this perhaps be listed on MELPA? I couldn't find it on MELPA.

Thanks in advance!

**Comment by MatthewBregg** [comment]
Thank you for the interest, I made a pull request to melpa, if it passes, then this package should be available there. 

https://github.com/milkypostman/melpa/pull/2902

**Comment by MatthewBregg** [comment]
It's now on melpa!
