### ISSUE TITLE
Complete neutral delimiters...?

### ISSUE THREAD

**Issue by jasonm23** [MatthewBregg/paren-completer#3]
It would  be great if neutral delimiters like `" '` and backticks could also be auto completed.

**Comment by MatthewBregg** [comment]
Thanks for the interest, it's something that I am currently working on.

**Comment by MatthewBregg** [comment]
Ok, I have made the branch.
https://github.com/MatthewBregg/paren-completer/tree/NuetralDelims
It currently only closes strings, but I think that should handle nearly every use case for neutral delimiters.

Let me know if that works for you, I plan to merge it into master soon.

**Comment by jasonm23** [comment]
Thank you very much, works well for me.

**Comment by MatthewBregg** [comment]
Glad to hear it.
I also added the option to ignore delimiters in strings and comments.
That is the new default behaviour, if you want to change it, see the readme for the variables to set to nil.
