### ISSUE TITLE
some customize variable which controls behavior when stack is vacant

### ISSUE THREAD

**Issue by lurdan** [MatthewBregg/paren-completer#8]
For now, I call paren-completer by pressing ")", and want paren-completer to insert
")" when its calculated stack is vacant, instead of ignoring pressed key with message.

I re-defined paren-completer--add-delimiter as "(if (eq delimiter-stack nil) (insert-char last-input-event)",
cf. https://github.com/MatthewBregg/paren-completer/blob/master/paren-completer.el#L133

It's a bit hacky for requesting PR, so I think that it had better it would have some options to change its behavior... how about?

**Comment by MatthewBregg** [comment]
Ok, try the newest version and let me know if that works.
You will want to customize paren-completer-default-delimiter to ?), and if you don't want it to print a message, then set paren-completer-print-message-if-emptyp? to nil. 

I'm a bit curious as to what situation you need that behaviour though, if you don't mind telling.  

Anyway, let me know if that works for you, and if you run into any other issues/have any other requests.

**Comment by lurdan** [comment]
Great thanks for your so quick reply, and sorry for my late reaction and lack of clarity.

I'm happy now customizing default-delimiter to be last-input-event's alias. :+1:

Background:I use paren-completer with config like this. niche usecase indeed,

> (use-package paren-completer
>  :ensure t
>  :bind ((")" . my--paren-completer)
>         ("]" . my--paren-completer)
>         ("}" . my--paren-completer)
>         )
>  :config
>  (defvaralias 'paren-completer-default-delimiter 'last-input-event)
>  (defun my--paren-completer ()
>    (interactive)
>    (if current-prefix-arg
>        (paren-completer-add-all-delimiters)
>      (paren-completer-add-single-delimiter)
>      ))
>  )

In paren-completer context, I can close paired parens by pressing any of closing paren key. Though I basically try to type "correct" key, this config help me from typo and my lazy mood.

On the other hand, I occasionally want to type closing paren without opening it, for example
creating byhand-numbered-list, 1), 2), ...and so on.
Sure, `C-q )` may work, but I want  paren-completer to work on its own (only when there are
open parens before cursor).

minibuffer message is useful for me as it tell me that "now you are out of paren-completer context".

Thanks again your nice package!

**Comment by MatthewBregg** [comment]
Ah, I see, that's a clever way to use it, I hadn't thought of using it like that.

I'm glad you enjoy the package, and thanks for the feedback!
